[mds-policy-author][mds-db]Adding /admin/policies and /admin/policies/:policy_uuid and /admin/geographies/:geography_uuid to mds-policy-author.
CityOfLosAngeles/mds-core pull request #135
Opened 2019-08-28 04:38 UTC by janedotx

## PR Checklist

 - [ ] simple searchable title - `[mds-db] Add PG env var`, `[config] Fix eslint config`
 - [ ] briefly describe the changes in this PR
 - [ ] mark as draft if should not be merged
 - [ ] write tests for all new functionality

## Impacts
- [ ] Provider
- [ ] Agency
- [ ] Audit
- [x] Policy
- [ ] Compliance

2019-08-28 14:08 UTC, mdurling requested changes

2019-08-28 17:25 UTC, avatarneil requested changes

2019-08-29 21:37 UTC, janedotx commented on packages/mds-policy-author/api.ts
> +      if (err.message.includes(db.NOT_FOUND)) {
sounds good

2019-08-29 23:19 UTC, janedotx commented
I'm giving up on this branch. New PR up at https://github.com/CityOfLosAngeles/mds-core/pull/142.

2019-08-29 23:19 UTC, closed without merging